# CLASE 3

In [ ]:
import numpy as np

In [11]:
def dataset(muestras, features):
    
    '''Crea un dataset'''
    
    x = np.zeros((muestras,features))

    for i in range(features):
        mu = np.random.randint(100)
        sigma = np.random.randint(1,10)
        x[:,i] = np.random.normal(mu, sigma, muestras)
    
    return x

In [ ]:
x1 = dataset(10,5)
print(x1)

## Ejercicio 1: Normalización
Muchos algoritmos de Machine Learning necesitan datos de entrada centrados y normalizados. Una normalización habitual es el z-score, que implica restarle la media y dividir por el desvío a cada feature de mi dataset.
Dado un dataset X de n muestras y m features, implementar un método en numpy para normalizar con z-score. Pueden utilizar np.mean() y np.std().

In [12]:
def zscore(x):
    return (x - x.mean(axis=0))/x.std(axis=0)

In [14]:
print(zscore(x1))

[[-0.35584077  1.58792417  1.91747651 -0.28064966 -2.1393887 ]
 [-0.29908421 -1.0259985  -0.17111784  0.88867057 -0.89852575]
 [ 0.79464306  0.33829663  0.15580479 -0.58055939 -1.01896333]
 [ 1.26412749  0.90343262 -0.75867638  1.33708586  1.32611042]
 [ 0.65439746 -0.53513608 -0.08797972  0.98469524  0.13519131]
 [-2.01122158  0.41771199 -0.29545662 -2.05637708  0.47962712]
 [ 0.98502172  0.92133742  0.63471915 -0.63067693  0.72445328]
 [ 0.72622817 -0.96177296 -1.69064532 -0.63642413  0.63833004]
 [-0.74171729 -1.79915169  1.21896091 -0.02814174  0.79763298]
 [-1.01655405  0.1533564  -0.92308546  1.00237726 -0.04446736]]


### Agregar elementos NaN aleatorios

In [75]:
def nanvalues(data):
    
    """Esta funcion agrega valores NaN a un dataset de forma aleatoria"""
    
    muestras, features = data.shape
    
    for feature in range(features):
        #Cantidad de valores NaN que tendra el feature
        value = np.random.randint(1,4)
        
        idx = np.random.randint(0,muestras,(muestras//value,1))
        data[np.unique(idx),feature] = np.NaN
    return data

## NaN evaluation

### Ejercicio 2: Remover filas y columnas con NaNs en un dataset
Dado un dataset, hacer una función que, utilizando numpy, filtre las columnas y las filas que tienen NaNs.

### Ejercicio 3: Reemplazar NaNs por la media de la columna.
Dado un dataset, hacer una función que utilizando numpy reemplace los NaNs por la media de la columna.

In [94]:
def nan_evaluation(dataset, threshold_muestra = 0.8, threshold_feature = 0.5):
    """
    1ro: Elimina las muestras del dataset que superan threshold_muestra*nro_feature en cantidad de NaN.
    
    2do: Elimina los features del dataset que superen threshold_feature*muestras en cantidad de NaN.
     
    3ro: Si la cantidad de NaN es menor entonces lo reemplza por la media.
    """
    dataset_bool = np.isnan(dataset)
    clean_dataset = np.delete(dataset, np.argwhere((np.sum(dataset_bool, axis=1) >= threshold_muestra*dataset.shape[1]) == True), axis = 0)
    
    dataset_bool = np.isnan(clean_dataset)
    clean_dataset = np.delete(clean_dataset, np.argwhere((np.sum(dataset_bool, axis=0) >= threshold_feature*clean_dataset.shape[0]) == True), axis = 1)

    dataset_bool = np.isnan(clean_dataset)
    for feature in range(clean_dataset.shape[1]):
        clean_dataset[dataset_bool[:,feature]==True, feature] = clean_dataset[dataset_bool[:,feature]==False, feature].mean()
    
    return clean_dataset

In [87]:
x = nanvalues(dataset(20,5))
print(x)

[[18.42762342         nan 56.77623424 35.17573623         nan]
 [23.71409567 77.63707535         nan 31.8317243          nan]
 [25.58161669 81.87441848         nan         nan         nan]
 [19.08486918 77.53187678 46.5550717  30.7673192          nan]
 [18.73017753 86.81121379 52.48747424 23.90849744  4.64244059]
 [        nan         nan 41.36347117         nan         nan]
 [22.45735407 77.08153179         nan 34.79856169  5.70423764]
 [22.68439264 84.88057597 41.97937385         nan         nan]
 [16.82630365 84.0273469          nan         nan         nan]
 [14.42641053 74.27374702 58.60159917 30.67524204  3.35194073]
 [17.82759614         nan 62.27384929         nan  6.42232994]
 [19.55514883 82.12392029 52.7407611  40.89030699         nan]
 [23.64064712 90.43578022 41.32780542 35.77283044         nan]
 [        nan 77.20343164         nan 38.21091005  4.45044392]
 [21.37501746         nan         nan         nan  7.2235319 ]
 [        nan 80.61845873 45.90638066 32.04201     4.59

In [96]:
clean_dataset = nan_evaluation(x, 0.6, 0.5)
print(clean_dataset.shape)
print()
print(clean_dataset)

(15, 4)

[[18.42762342 81.16779524 56.77623424 35.17573623]
 [23.71409567 77.63707535 50.08693847 31.8317243 ]
 [19.08486918 77.53187678 46.5550717  30.7673192 ]
 [18.73017753 86.81121379 52.48747424 23.90849744]
 [22.45735407 77.08153179 50.08693847 34.79856169]
 [22.68439264 84.88057597 41.97937385 33.05873825]
 [14.42641053 74.27374702 58.60159917 30.67524204]
 [17.82759614 81.16779524 62.27384929 33.05873825]
 [19.55514883 82.12392029 52.7407611  40.89030699]
 [23.64064712 90.43578022 41.32780542 35.77283044]
 [19.52310192 77.20343164 50.08693847 38.21091005]
 [19.52310192 80.61845873 45.90638066 32.04201   ]
 [19.52310192 85.76532425 44.91045378 34.50663381]
 [20.18289713 77.67055182 47.3973197  32.84104554]
 [13.54601081 83.14785044 50.08693847 28.34277951]]
