<a href="https://colab.research.google.com/github/AguAcerbo/VisionPorComputadora2/blob/main/deteccion_bordes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Veamos el ejemplo en las slides

In [1]:
# detección de bordes:
import numpy as np
np.random.seed(0)
img = np.random.randint(0, 10, size=(5,5), dtype='l')
filtro = np.array([[1,0,-1],
                   [1,0,-1],
                   [1,0,-1]])
print(img)
print()
print(filtro)

[[5 0 3 3 7]
 [9 3 5 2 4]
 [7 6 8 8 1]
 [6 7 7 8 1]
 [5 9 8 9 4]]

[[ 1  0 -1]
 [ 1  0 -1]
 [ 1  0 -1]]


### Multiplicación elemento a elemento y suma

In [2]:
np.sum(np.sum(img[0:3,0:3]*filtro))

5

In [3]:
np.sum(np.sum(img[1:4,0:3]*filtro))

2

In [4]:
img = np.repeat([[10,10,10,0,0,0]], 6, axis=0)
print(img)

[[10 10 10  0  0  0]
 [10 10 10  0  0  0]
 [10 10 10  0  0  0]
 [10 10 10  0  0  0]
 [10 10 10  0  0  0]
 [10 10 10  0  0  0]]


### Convolucionar la imagen entera y ver el resultado

In [5]:
# usamos scipy.signal.convolve2d
from scipy.signal import convolve2d
convolve2d(img,filtro,'valid')

array([[  0, -30, -30,   0],
       [  0, -30, -30,   0],
       [  0, -30, -30,   0],
       [  0, -30, -30,   0]])

In [6]:
# ejemplo de filtro horizontal:
import numpy as np
np.random.seed(0)
img = np.random.randint(0, 10, size=(5,5), dtype='l')
filtro = np.array([[1,1,1],
                   [0,0,0],
                   [-1,-1,-1]])
print(img)
print(filtro)

[[5 0 3 3 7]
 [9 3 5 2 4]
 [7 6 8 8 1]
 [6 7 7 8 1]
 [5 9 8 9 4]]
[[ 1  1  1]
 [ 0  0  0]
 [-1 -1 -1]]


In [7]:
img = np.array(
    [[10,10,10,0,0,0],
     [10,10,10,0,0,0],
     [10,10,10,0,0,0],
     [0,0,0,10,10,10],
     [0,0,0,10,10,10],
     [0,0,0,10,10,10]]
)
print(img)

[[10 10 10  0  0  0]
 [10 10 10  0  0  0]
 [10 10 10  0  0  0]
 [ 0  0  0 10 10 10]
 [ 0  0  0 10 10 10]
 [ 0  0  0 10 10 10]]


In [8]:
# convolucionamos
from scipy.signal import convolve2d
convolve2d(img,filtro,'valid')

array([[  0,   0,   0,   0],
       [-30, -10,  10,  30],
       [-30, -10,  10,  30],
       [  0,   0,   0,   0]])

In [9]:
convolve2d(img,filtro,'same')

array([[ 20,  30,  20,  10,   0,   0],
       [  0,   0,   0,   0,   0,   0],
       [-20, -30, -10,  10,  30,  20],
       [-20, -30, -10,  10,  30,  20],
       [  0,   0,   0,   0,   0,   0],
       [  0,   0, -10, -20, -30, -20]])