<a href="https://colab.research.google.com/github/AguAcerbo/DeepLearning/blob/main/Clase_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

EJEMPLO NO LINEAL FUNCION XOR

In [2]:
x=np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]]) 
# a la tabla de la verdad de la xor se le agrega una columna de unos de modo de adicionar la ordenada al origen
x

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [3]:
y = np.array([0,1,1,0])
y

array([0, 1, 1, 0])

In [4]:
w = (np.linalg.inv(x.T @ x)) @ x.T @ y
w

array([1.66533454e-16, 5.55111512e-17, 5.00000000e-01])

Esto es un ejemplo de porque a veces necesitamos modelos no lineales. En este caso la funcion XOR no es lineal y nuestro modelo lo trata de manera lineal por lo que la optimizacion llega a obtener un valor $w_0=0.5$. 

## Modelizado No Lineal de la funcion XOR

In [5]:
def sigmoid(z):
        return 1/(1+np.exp(-z))

In [6]:
def dsig(z):
    return sigmoid(z)*(1-sigmoid(z))

In [7]:
def test(x, y, w11_1, w12_1, b1_1, w21_1, w22_1, b2_1, w11_2, w12_2, b1_2):
    J = 0
    
    for sample in range(x.shape[0]):
        z1_1 = w11_1 * x[sample,1] + w12_1 * x[sample,0] + b1_1
        a1_1 = sigmoid(z1_1)
            
        z2_1 = w21_1 * x[sample,1] + w22_1 * x[sample,0] + b2_1
        a2_1 = sigmoid(z2_1)
            
        z1_2 = w11_2 * a1_1 + w12_2 * a2_1 + b1_2
        y_hat = z1_2
        J += (y[sample]-y_hat)**2
        print(f"Valor real: {y[sample]}\tPrediccion: {np.around(y_hat)}\tError: {J}")
    print(f"Error del modelo {J/x.shape[0]}")

In [8]:
def logic_gates_model(x, y, epochs=1000, lr=0.1, eps = 1):
    
    # Params Neurona 1 Layer 1
    w11_1 = (np.random.rand() * (2*eps) - eps)
    w12_1 = (np.random.rand() * (2*eps) - eps)
    b1_1 = (np.random.rand() * (2*eps) - eps)

    # Params Neurona 2 Layer 1
    w21_1 = (np.random.rand() * (2*eps) - eps)
    w22_1 = (np.random.rand() * (2*eps) - eps)
    b2_1 = (np.random.rand() * (2*eps) - eps)

    # Params Neurona 1 Layer 2
    w11_2 = (np.random.rand() * (2*eps) - eps)
    w12_2 = (np.random.rand() * (2*eps) - eps)
    b1_2 = (np.random.rand() * (2*eps) - eps)

    for epoch in range(epochs):
        for sample in range(x.shape[0]):
            #*****Forward*****
            # Neurona 1 Layer 1
            z1_1 = w11_1 * x[sample,1] + w12_1 * x[sample,0] + b1_1
            a1_1 = sigmoid(z1_1)

            # Neurona 2 Layer 1
            z2_1 = w21_1 * x[sample,1] + w22_1 * x[sample,0] + b2_1
            a2_1 = sigmoid(z2_1)

            # Neurona 1 Layer 2
            z1_2 = w11_2 * a1_1 + w12_2 * a2_1 + b1_2
            #a1_2 = sigmoid(z1_2)
            y_hat = z1_2

            #*****Loss Function*****
            J = (y[sample]-y_hat)**2

            dJ_w11_1 = -2*(y[sample]-y_hat) * w11_2 * dsig(z1_1) * x[sample,1]
            dJ_w12_1 = -2*(y[sample]-y_hat) * w11_2 * dsig(z1_1) * x[sample,0]
            dJ_b1_1 = -2*(y[sample]-y_hat) * w11_2 * dsig(z1_1)

            dJ_w21_1 = -2*(y[sample]-y_hat) * w12_2 * dsig(z2_1) * x[sample,1]
            dJ_w22_1 = -2*(y[sample]-y_hat) * w12_2 * dsig(z2_1) * x[sample,0]
            dJ_b2_1 = -2*(y[sample]-y_hat) * w12_2 * dsig(z2_1)

            dJ_w11_2 = -2*(y[sample]-y_hat) * a1_1
            dJ_w12_2 = -2*(y[sample]-y_hat) * a2_1
            dJ_b1_2 = -2*(y[sample]-y_hat)

            #*****Backward*****

            # Params Neurona 1 Layer 1
            w11_1 = w11_1 - lr * dJ_w11_1
            w12_1 = w12_1 - lr * dJ_w12_1
            b1_1 = b1_1 - lr * dJ_b1_1

            # Params Neurona 2 Layer 1
            w21_1 = w21_1 - lr * dJ_w21_1
            w22_1 = w22_1 - lr * dJ_w22_1
            b2_1 = b2_1 - lr * dJ_b2_1

            # Params Neurona 1 Layer 2
            w11_2 = w11_2 - lr * dJ_w11_2
            w12_2 = w12_2 - lr * dJ_w12_2
            b1_2 = b1_2 - lr * dJ_b1_2
            
    return w11_1, w12_1, b1_1, w21_1, w22_1, b2_1, w11_2, w12_2, b1_2

In [9]:
x=np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]])

In [10]:
# XOR Truth Table
y_xor = np.array([0,1,1,0])

w11_1, w12_1, b1_1, w21_1, w22_1, b2_1, w11_2, w12_2, b1_2 = logic_gates_model(x, y_xor, epochs=1000, lr=0.5, eps = 1)
test(x, y_xor, w11_1, w12_1, b1_1, w21_1, w22_1, b2_1, w11_2, w12_2, b1_2)

Valor real: 0	Prediccion: 0.0	Error: 4.437342591868191e-31
Valor real: 1	Prediccion: 1.0	Error: 2.2186712959340957e-30
Valor real: 1	Prediccion: 1.0	Error: 2.267975102510409e-30
Valor real: 0	Prediccion: 0.0	Error: 2.465190328815662e-30
Error del modelo 6.162975822039155e-31


In [11]:
# AND Truth Table
y_and = np.array([0,0,0,1])

w11_1, w12_1, b1_1, w21_1, w22_1, b2_1, w11_2, w12_2, b1_2 = logic_gates_model(x, y_and, epochs=1000, lr=0.5, eps = 1)
test(x, y_and, w11_1, w12_1, b1_1, w21_1, w22_1, b2_1, w11_2, w12_2, b1_2)

Valor real: 0	Prediccion: 0.0	Error: 0.0
Valor real: 0	Prediccion: 0.0	Error: 0.0
Valor real: 0	Prediccion: 0.0	Error: 0.0
Valor real: 1	Prediccion: 1.0	Error: 1.232595164407831e-32
Error del modelo 3.0814879110195774e-33


In [12]:
# OR Truth Table
y_or = np.array([0,1,1,1])

w11_1, w12_1, b1_1, w21_1, w22_1, b2_1, w11_2, w12_2, b1_2 = logic_gates_model(x, y_or, epochs=1000, lr=0.8, eps = 1)
test(x, y_or, w11_1, w12_1, b1_1, w21_1, w22_1, b2_1, w11_2, w12_2, b1_2)

Valor real: 0	Prediccion: 0.0	Error: 3.985671705574689e-08
Valor real: 1	Prediccion: 1.0	Error: 1.0144159315934491e-06
Valor real: 1	Prediccion: 1.0	Error: 0.00011973900005495164
Valor real: 1	Prediccion: 1.0	Error: 0.0001668768426416756
Error del modelo 4.17192106604189e-05


In [13]:
# NOR Truth Table
y_nor = np.array([1,0,0,0])

w11_1, w12_1, b1_1, w21_1, w22_1, b2_1, w11_2, w12_2, b1_2 = logic_gates_model(x, y_nor, epochs=1000, lr=0.5, eps = 1)
test(x, y_nor, w11_1, w12_1, b1_1, w21_1, w22_1, b2_1, w11_2, w12_2, b1_2)

Valor real: 1	Prediccion: 1.0	Error: 7.100056287473981e-07
Valor real: 0	Prediccion: 0.0	Error: 1.2025391787830967e-06
Valor real: 0	Prediccion: 0.0	Error: 0.00045877572021665934
Valor real: 0	Prediccion: 0.0	Error: 0.0004587781912473017
Error del modelo 0.00011469454781182543


In [14]:
# NAND Truth Table
y_nand = np.array([1,1,1,0])

w11_1, w12_1, b1_1, w21_1, w22_1, b2_1, w11_2, w12_2, b1_2 = logic_gates_model(x, y_nand, epochs=1000, lr=0.5, eps = 1)
test(x, y_nand, w11_1, w12_1, b1_1, w21_1, w22_1, b2_1, w11_2, w12_2, b1_2)

Valor real: 1	Prediccion: 1.0	Error: 8.903740253250567e-05
Valor real: 1	Prediccion: 1.0	Error: 0.00015032163803022902
Valor real: 1	Prediccion: 1.0	Error: 0.00015050195370258765
Valor real: 0	Prediccion: -0.0	Error: 0.00015146150121997018
Error del modelo 3.7865375304992546e-05


In [15]:
# XNOR Truth Table
y_xnor = np.array([1,0,0,1])

w11_1, w12_1, b1_1, w21_1, w22_1, b2_1, w11_2, w12_2, b1_2 = logic_gates_model(x, y_xnor, epochs=1000, lr=0.5, eps = 1)
test(x, y_xnor, w11_1, w12_1, b1_1, w21_1, w22_1, b2_1, w11_2, w12_2, b1_2)

Valor real: 1	Prediccion: 1.0	Error: 6.039716305598372e-31
Valor real: 0	Prediccion: -0.0	Error: 1.0477058897466563e-30
Valor real: 0	Prediccion: -0.0	Error: 1.2449211160519093e-30
Valor real: 1	Prediccion: 1.0	Error: 1.2449211160519093e-30
Error del modelo 3.112302790129773e-31
