<a href="https://colab.research.google.com/github/AguAcerbo/DeepLearning/blob/main/Clase_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

EJEMPLO NO LINEAL FUNCION XOR

In [2]:
x=np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]]) 
# a la tabla de la verdad de la xor se le agrega una columna de unos de modo de adicionar la ordenada al origen
x

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [3]:
y = np.array([0,1,1,0])
y

array([0, 1, 1, 0])

In [4]:
w = (np.linalg.inv(x.T @ x)) @ x.T @ y
w

array([1.66533454e-16, 5.55111512e-17, 5.00000000e-01])

Esto es un ejemplo de porque a veces necesitamos modelos no lineales. En este caso la funcion XOR no es lineal y nuestro modelo lo trata de manera lineal por lo que la optimizacion llega a obtener un valor $w_0=0.5$. 

## Modelizado No Lineal de compuertas logicas

In [5]:
def sigmoid(z):
        return 1/(1+np.exp(-z))

In [6]:
def dsig(z):
    return sigmoid(z)*(1-sigmoid(z))

In [7]:
# Inferencia
def test(x, y, w11_1, w12_1, b1_1, w21_1, w22_1, b2_1, w11_2, w12_2, b1_2):
    J = 0
    
    for sample in range(x.shape[0]):
        z1_1 = w11_1 * x[sample,1] + w12_1 * x[sample,0] + b1_1
        a1_1 = sigmoid(z1_1)
            
        z2_1 = w21_1 * x[sample,1] + w22_1 * x[sample,0] + b2_1
        a2_1 = sigmoid(z2_1)
            
        z1_2 = w11_2 * a1_1 + w12_2 * a2_1 + b1_2
        y_hat = z1_2
        J += (y[sample]-y_hat)**2
        print(f"Valor real: {y[sample]}\tPrediccion: {np.around(y_hat)}\tError: {J}")
    print(f"Error del modelo {J/x.shape[0]}")

In [8]:
def logic_gates_model(x, y, epochs=1000, lr=0.1, eps = 1):
    
    # Params Neurona 1 Layer 1
    w11_1 = (np.random.rand() * (2*eps) - eps)
    w12_1 = (np.random.rand() * (2*eps) - eps)
    b1_1 = (np.random.rand() * (2*eps) - eps)

    # Params Neurona 2 Layer 1
    w21_1 = (np.random.rand() * (2*eps) - eps)
    w22_1 = (np.random.rand() * (2*eps) - eps)
    b2_1 = (np.random.rand() * (2*eps) - eps)

    # Params Neurona 1 Layer 2
    w11_2 = (np.random.rand() * (2*eps) - eps)
    w12_2 = (np.random.rand() * (2*eps) - eps)
    b1_2 = (np.random.rand() * (2*eps) - eps)

    for epoch in range(epochs): # loop in epochs
        index = np.random.permutation(x.shape[0])
        x = x[index, :]
        y = y[index]
        for sample in range(x.shape[0]): # loop in barches
            #*****Forward*****
            # Neurona 1 Layer 1
            z1_1 = w11_1 * x[sample,1] + w12_1 * x[sample,0] + b1_1
            a1_1 = sigmoid(z1_1)

            # Neurona 2 Layer 1
            z2_1 = w21_1 * x[sample,1] + w22_1 * x[sample,0] + b2_1
            a2_1 = sigmoid(z2_1)

            # Neurona 1 Layer 2
            z1_2 = w11_2 * a1_1 + w12_2 * a2_1 + b1_2
            #a1_2 = sigmoid(z1_2)
            y_hat = z1_2

            #*****Loss Function*****
            error = y[sample]-y_hat 
            J = error**2
            
            #*****Backward*****
            dJ_w11_1 = -2*error * w11_2 * dsig(z1_1) * x[sample,1]
            dJ_w12_1 = -2*error * w11_2 * dsig(z1_1) * x[sample,0]
            dJ_b1_1 = -2*error * w11_2 * dsig(z1_1)

            dJ_w21_1 = -2*error * w12_2 * dsig(z2_1) * x[sample,1]
            dJ_w22_1 = -2*error * w12_2 * dsig(z2_1) * x[sample,0]
            dJ_b2_1 = -2*error * w12_2 * dsig(z2_1)

            dJ_w11_2 = -2*error * a1_1
            dJ_w12_2 = -2*error * a2_1
            dJ_b1_2 = -2*error * 1

            #*****Updates of weights*****

            # Params Neurona 1 Layer 1
            w11_1 = w11_1 - lr * dJ_w11_1
            w12_1 = w12_1 - lr * dJ_w12_1
            b1_1 = b1_1 - lr * dJ_b1_1

            # Params Neurona 2 Layer 1
            w21_1 = w21_1 - lr * dJ_w21_1
            w22_1 = w22_1 - lr * dJ_w22_1
            b2_1 = b2_1 - lr * dJ_b2_1

            # Params Neurona 1 Layer 2
            w11_2 = w11_2 - lr * dJ_w11_2
            w12_2 = w12_2 - lr * dJ_w12_2
            b1_2 = b1_2 - lr * dJ_b1_2
            
    return w11_1, w12_1, b1_1, w21_1, w22_1, b2_1, w11_2, w12_2, b1_2

In [9]:
x=np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]])

In [16]:
# XOR Truth Table
y_xor = np.array([0,1,1,0])

w11_1, w12_1, b1_1, w21_1, w22_1, b2_1, w11_2, w12_2, b1_2 = logic_gates_model(x, y_xor, epochs=1000, lr=0.4, eps = 1)
test(x, y_xor, w11_1, w12_1, b1_1, w21_1, w22_1, b2_1, w11_2, w12_2, b1_2)

Valor real: 0	Prediccion: 0.0	Error: 1.232595164407831e-30
Valor real: 1	Prediccion: 1.0	Error: 1.232595164407831e-30
Valor real: 1	Prediccion: 1.0	Error: 1.232595164407831e-30
Valor real: 0	Prediccion: -0.0	Error: 1.3096323621833204e-30
Error del modelo 3.274080905458301e-31


In [17]:
# AND Truth Table
y_and = np.array([0,0,0,1])

w11_1, w12_1, b1_1, w21_1, w22_1, b2_1, w11_2, w12_2, b1_2 = logic_gates_model(x, y_and, epochs=1000, lr=0.5, eps = 1)
test(x, y_and, w11_1, w12_1, b1_1, w21_1, w22_1, b2_1, w11_2, w12_2, b1_2)

Valor real: 0	Prediccion: -0.0	Error: 1.740667436819862e-08
Valor real: 0	Prediccion: 0.0	Error: 2.2155452350171518e-08
Valor real: 0	Prediccion: -0.0	Error: 2.2192853272363846e-08
Valor real: 1	Prediccion: 1.0	Error: 7.718617567481028e-08
Error del modelo 1.929654391870257e-08


In [18]:
# OR Truth Table
y_or = np.array([0,1,1,1])

w11_1, w12_1, b1_1, w21_1, w22_1, b2_1, w11_2, w12_2, b1_2 = logic_gates_model(x, y_or, epochs=1000, lr=0.8, eps = 1)
test(x, y_or, w11_1, w12_1, b1_1, w21_1, w22_1, b2_1, w11_2, w12_2, b1_2)

Valor real: 0	Prediccion: 0.0	Error: 0.0023408685946813973
Valor real: 1	Prediccion: 1.0	Error: 0.0023417816699729224
Valor real: 1	Prediccion: 1.0	Error: 0.0023435720209333817
Valor real: 1	Prediccion: 1.0	Error: 0.0036293883123044712
Error del modelo 0.0009073470780761178


In [19]:
# NOR Truth Table
y_nor = np.array([1,0,0,0])

w11_1, w12_1, b1_1, w21_1, w22_1, b2_1, w11_2, w12_2, b1_2 = logic_gates_model(x, y_nor, epochs=1000, lr=0.5, eps = 1)
test(x, y_nor, w11_1, w12_1, b1_1, w21_1, w22_1, b2_1, w11_2, w12_2, b1_2)

Valor real: 1	Prediccion: 1.0	Error: 1.6498927496457985e-16
Valor real: 0	Prediccion: -0.0	Error: 2.8365821658883497e-16
Valor real: 0	Prediccion: -0.0	Error: 3.1391712558688476e-16
Valor real: 0	Prediccion: -0.0	Error: 1.8596044575302422e-15
Error del modelo 4.649011143825606e-16


In [24]:
# NAND Truth Table
y_nand = np.array([1,1,1,0])

w11_1, w12_1, b1_1, w21_1, w22_1, b2_1, w11_2, w12_2, b1_2 = logic_gates_model(x, y_nand, epochs=1000, lr=0.5, eps = 1)
test(x, y_nand, w11_1, w12_1, b1_1, w21_1, w22_1, b2_1, w11_2, w12_2, b1_2)

Valor real: 1	Prediccion: 1.0	Error: 0.0
Valor real: 1	Prediccion: 1.0	Error: 0.0
Valor real: 1	Prediccion: 1.0	Error: 0.0
Valor real: 0	Prediccion: 0.0	Error: 0.0
Error del modelo 0.0


In [25]:
# XNOR Truth Table
y_xnor = np.array([1,0,0,1])

w11_1, w12_1, b1_1, w21_1, w22_1, b2_1, w11_2, w12_2, b1_2 = logic_gates_model(x, y_xnor, epochs=1000, lr=0.4, eps = 1)
test(x, y_xnor, w11_1, w12_1, b1_1, w21_1, w22_1, b2_1, w11_2, w12_2, b1_2)

Valor real: 1	Prediccion: 1.0	Error: 0.0
Valor real: 0	Prediccion: 0.0	Error: 0.0
Valor real: 0	Prediccion: 0.0	Error: 0.0
Valor real: 1	Prediccion: 1.0	Error: 1.232595164407831e-32
Error del modelo 3.0814879110195774e-33
